import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    cli: "src/cli.ts",
    runner: "src/runner.ts",
    "runtime/worker": "src/runtime/worker.ts",
    "builtin-connectors/postgres": "src/builtin-connectors/postgres.ts",
    "builtin-connectors/mongodb": "src/builtin-connectors/mongodb.ts",
    "builtin-connectors/redis": "src/builtin-connectors/redis.ts",
    "builtin-connectors/smtp": "src/builtin-connectors/smtp.ts",
    "builtin-connectors/md-emoji-remover": "src/builtin-connectors/md-emoji-remover.ts",
    "builtin-connectors/md-bold-italic-cleaner": "src/builtin-connectors/md-bold-italic-cleaner.ts",
    "builtin-connectors/md-frontmatter-builder": "src/builtin-connectors/md-frontmatter-builder.ts",
    "builtin-connectors/md-toc-generator": "src/builtin-connectors/md-toc-generator.ts",
    "builtin-connectors/md-heading-shifter": "src/builtin-connectors/md-heading-shifter.ts",
    "builtin-connectors/md-image-path-rewriter": "src/builtin-connectors/md-image-path-rewriter.ts",
    "builtin-connectors/md-merger": "src/builtin-connectors/md-merger.ts",
    "builtin-connectors/md-minifier": "src/builtin-connectors/md-minifier.ts",
    "builtin-connectors/md-secret-redactor": "src/builtin-connectors/md-secret-redactor.ts",
    "builtin-connectors/md-list-fixer": "src/builtin-connectors/md-list-fixer.ts",
    "builtin-connectors/md-prettifier": "src/builtin-connectors/md-prettifier.ts",
    "builtin-connectors/md-lint": "src/builtin-connectors/md-lint.ts",
    "builtin-connectors/md-diff": "src/builtin-connectors/md-diff.ts",
    "builtin-connectors/md-link-validator": "src/builtin-connectors/md-link-validator.ts",
    "builtin-connectors/md-from-text": "src/builtin-connectors/md-from-text.ts",
    "builtin-connectors/md-splitter": "src/builtin-connectors/md-splitter.ts",
    "builtin-connectors/md-table-repair": "src/builtin-connectors/md-table-repair.ts",
    "builtin-connectors/md-math-normalizer": "src/builtin-connectors/md-math-normalizer.ts",
    "builtin-connectors/md-code-block-tagger": "src/builtin-connectors/md-code-block-tagger.ts",
    "builtin-connectors/md-footnote-linker": "src/builtin-connectors/md-footnote-linker.ts",
    "builtin-connectors/md-ref-link-converter": "src/builtin-connectors/md-ref-link-converter.ts",
    "builtin-connectors/md-gfm-to-commonmark": "src/builtin-connectors/md-gfm-to-commonmark.ts",
    "builtin-connectors/md-to-html": "src/builtin-connectors/md-to-html.ts",
    "builtin-connectors/md-to-github-html": "src/builtin-connectors/md-to-github-html.ts",
    "builtin-connectors/md-to-reveal": "src/builtin-connectors/md-to-reveal.ts",
    "builtin-connectors/md-to-slack": "src/builtin-connectors/md-to-slack.ts",
    "builtin-connectors/md-to-jira": "src/builtin-connectors/md-to-jira.ts",
  },
  format: ["esm"],
  target: "node20",
  platform: "node",
  outDir: "dist",
  clean: true,
  sourcemap: true,
  dts: { entry: { runner: "src/runner.ts" } },
  shims: true,
  splitting: false,
  // pg/mongodb/redis/nodemailer stay external — they're listed in dependencies
  // and must be loaded from node_modules at runtime (some have native bindings).
});
