using System.Security.Cryptography;
using System.Text;

namespace JadAppsRunner.Core;

/// <summary>
/// AES-256-GCM wire-format helpers, byte-for-byte compatible with the
/// Node implementation in <c>src/credentials/crypto.ts</c> and the Rust
/// implementation in <c>src-tauri/src/core/crypto.rs</c>.
/// </summary>
/// <remarks>
/// Wire format (base64-encoded):
/// <c>nonce(12) || ciphertext || tag(16)</c>
/// </remarks>
public static class AesGcm256
{
    private const int NonceLengthBytes = 12;
    private const int TagLengthBytes = 16;
    private const int KeyLengthBytes = 32;

    /// <summary>
    /// Encrypt and return the canonical base64 envelope.
    /// </summary>
    /// <param name="masterKeyBase64">
    /// 32-byte AES-256 key, base64-encoded. Generated by
    /// <c>generateMasterKey()</c> on the Node side.
    /// </param>
    public static string Encrypt(string masterKeyBase64, byte[] plaintext)
    {
        var key = Convert.FromBase64String(masterKeyBase64);
        if (key.Length != KeyLengthBytes)
        {
            throw new ArgumentException(
                $"AES-256 key must be {KeyLengthBytes} bytes, got {key.Length}",
                nameof(masterKeyBase64));
        }
        var nonce = RandomNumberGenerator.GetBytes(NonceLengthBytes);
        return EncryptWithNonce(key, nonce, plaintext);
    }

    /// <summary>
    /// Encrypt with a caller-supplied nonce. Used by parity tests so
    /// the output is deterministic; production should use the random
    /// overload.
    /// </summary>
    public static string EncryptWithNonce(byte[] key, byte[] nonce, byte[] plaintext)
    {
        if (key.Length != KeyLengthBytes)
        {
            throw new ArgumentException($"key must be {KeyLengthBytes} bytes", nameof(key));
        }
        if (nonce.Length != NonceLengthBytes)
        {
            throw new ArgumentException($"nonce must be {NonceLengthBytes} bytes", nameof(nonce));
        }
        var ciphertext = new byte[plaintext.Length];
        var tag = new byte[TagLengthBytes];
        using var aes = new AesGcm(key, TagLengthBytes);
        aes.Encrypt(nonce, plaintext, ciphertext, tag);

        var envelope = new byte[NonceLengthBytes + ciphertext.Length + TagLengthBytes];
        Buffer.BlockCopy(nonce, 0, envelope, 0, NonceLengthBytes);
        Buffer.BlockCopy(ciphertext, 0, envelope, NonceLengthBytes, ciphertext.Length);
        Buffer.BlockCopy(tag, 0, envelope, NonceLengthBytes + ciphertext.Length, TagLengthBytes);
        return Convert.ToBase64String(envelope);
    }

    /// <summary>Decrypt a base64 envelope produced by any of our impls.</summary>
    public static byte[] Decrypt(string masterKeyBase64, string envelopeBase64)
    {
        var key = Convert.FromBase64String(masterKeyBase64);
        if (key.Length != KeyLengthBytes)
        {
            throw new ArgumentException(
                $"AES-256 key must be {KeyLengthBytes} bytes, got {key.Length}",
                nameof(masterKeyBase64));
        }
        var envelope = Convert.FromBase64String(envelopeBase64);
        if (envelope.Length < NonceLengthBytes + TagLengthBytes)
        {
            throw new ArgumentException("envelope is shorter than nonce + tag overhead");
        }
        var nonce = envelope.AsSpan(0, NonceLengthBytes).ToArray();
        var ciphertextLen = envelope.Length - NonceLengthBytes - TagLengthBytes;
        var ciphertext = envelope.AsSpan(NonceLengthBytes, ciphertextLen).ToArray();
        var tag = envelope.AsSpan(NonceLengthBytes + ciphertextLen, TagLengthBytes).ToArray();
        var plaintext = new byte[ciphertextLen];
        using var aes = new AesGcm(key, TagLengthBytes);
        aes.Decrypt(nonce, ciphertext, tag, plaintext);
        return plaintext;
    }

    /// <summary>UTF-8 convenience wrapper around <see cref="Decrypt"/>.</summary>
    public static string DecryptUtf8(string masterKeyBase64, string envelopeBase64)
    {
        return Encoding.UTF8.GetString(Decrypt(masterKeyBase64, envelopeBase64));
    }

    /// <summary>UTF-8 convenience wrapper around <see cref="Encrypt"/>.</summary>
    public static string EncryptUtf8(string masterKeyBase64, string plaintext)
    {
        return Encrypt(masterKeyBase64, Encoding.UTF8.GetBytes(plaintext));
    }

    /// <summary>Generate a fresh 32-byte AES-256 master key, base64-encoded.</summary>
    public static string GenerateMasterKey()
    {
        return Convert.ToBase64String(RandomNumberGenerator.GetBytes(KeyLengthBytes));
    }
}
