/**
 * excel-python-gen: emits a Python script that loads the workbook into
 * pandas DataFrames and exposes one DataFrame variable per sheet. Useful as
 * a starting point for analysis notebooks.
 */

import { writeFile } from "node:fs/promises";
import { statSync } from "node:fs";
import { join } from "node:path";
import type { StepResult, FileRef } from "../types.js";

interface ToolContext {
  toolId: string;
  inputs: Record<string, unknown>;
  fileRefs: FileRef[];
  scratchDir: string;
  emitProgress(bytes: number): void;
}

export default async function excelPythonGen(ctx: ToolContext): Promise<StepResult> {
  const start = Date.now();
  const ref = ctx.fileRefs[0];
  if (!ref) return errorResult("missing_input", "excel-python-gen requires one .xlsx input");

  let ExcelJS: typeof import("exceljs");
  try { ExcelJS = (await import("exceljs")).default as typeof import("exceljs"); }
  catch (err) { return errorResult("driver_missing", `exceljs not installed: ${(err as Error).message}`); }

  const inPath = join(ctx.scratchDir, ref.ref);
  const totalIn = sizeOrFallback(inPath, ref.bytes);
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(inPath);
  ctx.emitProgress(totalIn);

  const sheets = wb.worksheets.map((sheet) => {
    const matrix: unknown[][] = [];
    sheet.eachRow({ includeEmpty: false }, (row) => matrix.push(Array.isArray(row.values) ? row.values.slice(1) : []));
    const header = (matrix[0] ?? []).map((v) => String(v ?? ""));
    const dtypes = inferDtypes(header, matrix.slice(1, 100));
    return { name: sheet.name, varName: pyName(sheet.name), header, dtypes, rowCount: Math.max(0, matrix.length - 1) };
  });

  const lines: string[] = [];
  lines.push("\"\"\"Generated by excel-python-gen — load the workbook into pandas DataFrames.\"\"\"");
  lines.push("import pandas as pd");
  lines.push("");
  lines.push(`PATH = "${(ref.filename ?? "input.xlsx").replace(/"/g, '\\"')}"`);
  lines.push("");
  for (const s of sheets) {
    lines.push(`# ${s.name} — ${s.rowCount} row(s)`);
    lines.push(`${s.varName} = pd.read_excel(PATH, sheet_name=${JSON.stringify(s.name)})`);
    if (s.dtypes.dates.length > 0) {
      lines.push(`${s.varName}[${formatList(s.dtypes.dates)}] = ${s.varName}[${formatList(s.dtypes.dates)}].apply(pd.to_datetime)`);
    }
    lines.push(`print(${JSON.stringify(s.name)}, ${s.varName}.shape)`);
    lines.push("");
  }

  const out = lines.join("\n");
  const outRef = "load_workbook.py";
  const outPath = join(ctx.scratchDir, outRef);
  await writeFile(outPath, out, "utf8");

  return {
    ok: true,
    outputs: { sheetCount: sheets.length },
    fileRefs: [{ ref: outRef, bytes: Buffer.byteLength(out, "utf8"), sha256: "", mime: "text/x-python", filename: outRef }],
    bytesProcessed: totalIn,
    durationMs: Date.now() - start,
  };
}

interface Dtypes { dates: string[]; }

function inferDtypes(header: string[], sample: unknown[][]): Dtypes {
  const dates: string[] = [];
  for (let i = 0; i < header.length; i++) {
    let dateLike = 0, total = 0;
    for (const row of sample) {
      const v = row[i];
      if (v == null) continue;
      total += 1;
      if (v instanceof Date) dateLike += 1;
      else if (typeof v === "string" && !Number.isNaN(Date.parse(v)) && /\d{4}/.test(v)) dateLike += 1;
    }
    if (total > 0 && dateLike / total > 0.7) dates.push(header[i]!);
  }
  return { dates };
}

function pyName(s: string): string {
  let n = s.toLowerCase().replace(/[^a-z0-9_]/g, "_").replace(/^_+|_+$/g, "");
  if (!/^[a-z_]/.test(n)) n = "df_" + n;
  return n || "df";
}

function formatList(items: string[]): string {
  return "[" + items.map((s) => JSON.stringify(s)).join(", ") + "]";
}

function sizeOrFallback(path: string, fallback: number): number {
  try { return statSync(path).size; } catch { return fallback; }
}

function errorResult(code: string, message: string): StepResult {
  return { ok: false, outputs: {}, fileRefs: [], bytesProcessed: 0, durationMs: 0, error: { code, message } };
}
