/**
 * excel-trpc-router: generates a tRPC v11 router scaffold (with Zod schemas,
 * TypeScript interfaces, and full CRUD procedures) from an Excel workbook or
 * CSV file.
 *
 * Output is byte-identical to the in-process implementation in JAD Apps
 * (lib/excel/excel-code-gen.ts::buildTrpcRouter). Verified by the
 * reference-snapshot lock test in the main repo. Uses sheetjs (`xlsx`) to
 * read both .xlsx and .csv — same library, same version, as JAD Apps.
 */

import { readFile, writeFile } from "node:fs/promises";
import { statSync } from "node:fs";
import { join } from "node:path";
import * as XLSX from "xlsx";
import type { StepResult, FileRef } from "../types.js";

interface ToolContext {
  toolId: string;
  inputs: Record<string, unknown>;
  fileRefs: FileRef[];
  scratchDir: string;
  emitProgress(bytes: number): void;
}

type SpreadsheetRow = Record<string, unknown>;
type ColType = "number" | "string" | "boolean";
type Col = { name: string; type: ColType };

export default async function excelTrpcRouter(ctx: ToolContext): Promise<StepResult> {
  const start = Date.now();
  const ref = ctx.fileRefs[0];
  if (!ref) return errorResult("missing_input", "Upload an .xlsx or .csv file.");

  const inPath = join(ctx.scratchDir, ref.ref);
  const totalIn = sizeOrFallback(inPath, ref.bytes);
  const buf = await readFile(inPath);
  ctx.emitProgress(totalIn);

  const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
  const wb = XLSX.read(ab, { type: "array", cellDates: true });
  const sheetNames = wb.SheetNames;
  const sheets = sheetNames
    .map((name) => ({
      name,
      rows: XLSX.utils.sheet_to_json<SpreadsheetRow>(wb.Sheets[name]!, { defval: "", raw: false }),
    }))
    .filter((s) => s.rows.length > 0);

  const rawName = typeof ctx.inputs.routerName === "string" ? ctx.inputs.routerName : "";
  const cleanRouterName = rawName.trim() || "dataRouter";
  const filename = ref.filename ?? ref.ref;

  if (sheets.length === 0) {
    const out = "// No data\n";
    const outRef = `${cleanRouterName}.ts`;
    await writeFile(join(ctx.scratchDir, outRef), out, "utf8");
    return finishResult(outRef, out, 0, totalIn, start);
  }

  const totalRows = sheets.reduce((n, s) => n + s.rows.length, 0);
  const baseHeader = `/**
 * Auto-generated tRPC router.
 * Generated from: ${filename} (${sheets.length} sheet${sheets.length === 1 ? "" : "s"}, ${totalRows} rows)
 * Generated by JAD Excel Tools — https://jadapps.com/excel-tools
 */
import { z } from "zod";
import { router, publicProcedure, protectedProcedure } from "../trpc";
import { TRPCError } from "@trpc/server";`;

  let code: string;
  if (sheets.length === 1) {
    const cols = inferColumns(sheets[0]!.rows);
    const entityName = pascalCase(cleanRouterName.replace(/router$/i, "") || "Data");
    code = `${baseHeader}

// ─── Schema ───────────────────────────────────────────────────────────────────

${renderEntitySchema(entityName, cols)}

// ─── Router ───────────────────────────────────────────────────────────────────

export const ${cleanRouterName} = router({

${renderEntityProcedures(entityName, cols)}
});

export type ${entityName}Router = typeof ${cleanRouterName};
`;
  } else {
    const entities = sheets.map((s) => ({
      sheetName: s.name,
      rows: s.rows,
      entityName: pascalCase(s.name),
      fieldName: camelCase(s.name),
      cols: inferColumns(s.rows),
    }));
    const schemaBlocks = entities.map((e) => renderEntitySchema(e.entityName, e.cols)).join("\n\n");
    const subRouters = entities
      .map((e) => `const ${e.fieldName}Router = router({

${renderEntityProcedures(e.entityName, e.cols)}
});`)
      .join("\n\n");
    const rootEntries = entities.map((e) => `  ${e.fieldName}: ${e.fieldName}Router,`).join("\n");
    const rootTypeName = pascalCase(cleanRouterName);
    code = `${baseHeader}

// ─── Schemas ──────────────────────────────────────────────────────────────────

${schemaBlocks}

// ─── Sub-routers ──────────────────────────────────────────────────────────────

${subRouters}

// ─── Root router ──────────────────────────────────────────────────────────────

export const ${cleanRouterName} = router({
${rootEntries}
});

export type ${rootTypeName} = typeof ${cleanRouterName};
`;
  }

  const outRef = `${cleanRouterName}.ts`;
  await writeFile(join(ctx.scratchDir, outRef), code, "utf8");
  return finishResult(outRef, code, totalRows, totalIn, start);
}

function finishResult(outRef: string, code: string, totalRows: number, totalIn: number, start: number): StepResult {
  const bytes = Buffer.byteLength(code, "utf8");
  return {
    ok: true,
    outputs: { rows: totalRows, sizeBytes: bytes },
    fileRefs: [{ ref: outRef, bytes, sha256: "", mime: "text/typescript", filename: outRef }],
    bytesProcessed: totalIn,
    durationMs: Date.now() - start,
  };
}

// ── Column type inference (mirrors lib/excel/excel-code-gen.ts) ──────────────

function inferColumns(rows: SpreadsheetRow[]): Col[] {
  const headers = Object.keys(rows[0] ?? {});
  return headers.map((h) => {
    const samples = rows.slice(0, 50).map((r) => r[h]).filter((v) => v !== null && v !== undefined && v !== "");
    let type: ColType = "string";
    if (samples.length > 0) {
      if (samples.every((v) => typeof v === "number" || /^-?\d+(\.\d+)?$/.test(String(v)))) type = "number";
      else if (samples.every((v) => /^\d{4}-\d{2}-\d{2}/.test(String(v)))) type = "string";
      else if (samples.every((v) => v === true || v === false || v === "true" || v === "false")) type = "boolean";
    }
    return { name: h, type };
  });
}

const zodFor = (t: ColType) =>
  ({ number: "z.number()", string: "z.string()", boolean: "z.boolean()" })[t];
const tsFor = (t: ColType) =>
  ({ number: "number", string: "string", boolean: "boolean" })[t];

function pascalCase(s: string): string {
  return s.replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/^(.)/, (c) => c.toUpperCase());
}
function camelCase(s: string): string {
  const p = pascalCase(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

function renderEntitySchema(entityName: string, cols: Col[]): string {
  const camel = camelCase(entityName);
  const schemaName = `${entityName}Schema`;
  const zodFields = cols.map((c) => `  ${camelCase(c.name)}: ${zodFor(c.type)}.optional(),`).join("\n");
  const tsFields = cols.map((c) => `  ${camelCase(c.name)}?: ${tsFor(c.type)};`).join("\n");
  return `export const ${schemaName} = z.object({
${zodFields}
});

export const ${camel}CreateSchema = ${schemaName}.required();
export const ${camel}UpdateSchema = ${schemaName}.partial().extend({
  id: z.string().uuid(),
});

export interface ${entityName} {
${tsFields}
}`;
}

function renderEntityProcedures(entityName: string, cols: Col[]): string {
  const camel = camelCase(entityName);
  const searchableCols = cols.filter((c) => c.type === "string").slice(0, 2);
  const searchClause = searchableCols.length > 0
    ? `{ OR: [${searchableCols.map((c) => `{ ${camelCase(c.name)}: { contains: search, mode: "insensitive" } }`).join(", ")}] }`
    : `{}`;
  return `  /** Fetch all ${entityName} records (paginated) */
  list: publicProcedure
    .input(z.object({
      page: z.number().int().min(1).default(1),
      pageSize: z.number().int().min(1).max(100).default(20),
      search: z.string().optional(),
    }))
    .query(async ({ input, ctx }) => {
      const { page, pageSize, search } = input;
      // TODO: replace with your actual data source
      const data: ${entityName}[] = await ctx.db.${camel}.findMany({
        skip: (page - 1) * pageSize,
        take: pageSize,
        where: search ? ${searchClause} : undefined,
      });
      return { data, page, pageSize };
    }),

  /** Fetch a single ${entityName} by ID */
  getById: publicProcedure
    .input(z.object({ id: z.string().uuid() }))
    .query(async ({ input, ctx }) => {
      const record = await ctx.db.${camel}.findUnique({ where: { id: input.id } });
      if (!record) throw new TRPCError({ code: "NOT_FOUND", message: "${entityName} not found" });
      return record;
    }),

  /** Create a new ${entityName} */
  create: protectedProcedure
    .input(${camel}CreateSchema)
    .mutation(async ({ input, ctx }) => {
      return ctx.db.${camel}.create({ data: input });
    }),

  /** Update an existing ${entityName} */
  update: protectedProcedure
    .input(${camel}UpdateSchema)
    .mutation(async ({ input, ctx }) => {
      const { id, ...data } = input;
      return ctx.db.${camel}.update({ where: { id }, data });
    }),

  /** Delete a ${entityName} by ID */
  delete: protectedProcedure
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ input, ctx }) => {
      await ctx.db.${camel}.delete({ where: { id: input.id } });
      return { success: true };
    }),`;
}

function sizeOrFallback(path: string, fallback: number): number {
  try { return statSync(path).size; } catch { return fallback; }
}

function errorResult(code: string, message: string): StepResult {
  return { ok: false, outputs: {}, fileRefs: [], bytesProcessed: 0, durationMs: 0, error: { code, message } };
}
