/**
 * excel-trpc-router: emits a tRPC router scaffold (with Zod schemas) inferred
 * from the workbook structure. One router per sheet, with `list` and
 * `getById` procedures and a Zod object schema reflecting the sheet's
 * inferred column types.
 */

import { writeFile } from "node:fs/promises";
import { statSync } from "node:fs";
import { join } from "node:path";
import type { StepResult, FileRef } from "../types.js";

interface ToolContext {
  toolId: string;
  inputs: Record<string, unknown>;
  fileRefs: FileRef[];
  scratchDir: string;
  emitProgress(bytes: number): void;
}

export default async function excelTrpcRouter(ctx: ToolContext): Promise<StepResult> {
  const start = Date.now();
  const ref = ctx.fileRefs[0];
  if (!ref) return errorResult("missing_input", "excel-trpc-router requires one .xlsx input");

  let ExcelJS: typeof import("exceljs");
  try { ExcelJS = (await import("exceljs")).default as typeof import("exceljs"); }
  catch (err) { return errorResult("driver_missing", `exceljs not installed: ${(err as Error).message}`); }

  const inPath = join(ctx.scratchDir, ref.ref);
  const totalIn = sizeOrFallback(inPath, ref.bytes);
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(inPath);
  ctx.emitProgress(totalIn);

  const sheets = wb.worksheets.map((sheet) => {
    const matrix: unknown[][] = [];
    sheet.eachRow({ includeEmpty: false }, (row) => matrix.push(Array.isArray(row.values) ? row.values.slice(1) : []));
    const header = (matrix[0] ?? []).map((v) => String(v ?? ""));
    const types = header.map((_, i) => inferZod(matrix.slice(1, 50).map((r) => r[i])));
    return { name: sheet.name, routerName: camelCase(sheet.name), schemaName: pascalCase(sheet.name) + "Schema", header, types };
  });

  const lines: string[] = [];
  lines.push("// Generated by excel-trpc-router — wire each procedure to your data layer.");
  lines.push("import { z } from \"zod\";");
  lines.push("import { router, publicProcedure } from \"./trpc\";");
  lines.push("");
  for (const s of sheets) {
    const fields = s.header.map((h, i) => `  ${JSON.stringify(h)}: ${s.types[i]}`).join(",\n");
    lines.push(`export const ${s.schemaName} = z.object({\n${fields}\n});`);
    lines.push("");
    lines.push(`export const ${s.routerName}Router = router({`);
    lines.push(`  list: publicProcedure.query(async () => [] as z.infer<typeof ${s.schemaName}>[]),`);
    lines.push(`  getById: publicProcedure.input(z.object({ id: z.string() })).query(async ({ input }) => null as z.infer<typeof ${s.schemaName}> | null),`);
    lines.push("});");
    lines.push("");
  }
  lines.push("export const appRouter = router({");
  for (const s of sheets) lines.push(`  ${s.routerName}: ${s.routerName}Router,`);
  lines.push("});");
  lines.push("export type AppRouter = typeof appRouter;");

  const out = lines.join("\n");
  const outRef = "router.ts";
  const outPath = join(ctx.scratchDir, outRef);
  await writeFile(outPath, out, "utf8");

  return {
    ok: true,
    outputs: { sheetCount: sheets.length, routerCount: sheets.length },
    fileRefs: [{ ref: outRef, bytes: Buffer.byteLength(out, "utf8"), sha256: "", mime: "text/typescript", filename: outRef }],
    bytesProcessed: totalIn,
    durationMs: Date.now() - start,
  };
}

function inferZod(values: unknown[]): string {
  const present = values.filter((v) => v != null && v !== "");
  if (present.length === 0) return "z.unknown()";
  const allBool = present.every((v) => typeof v === "boolean");
  if (allBool) return "z.boolean()";
  const allNum = present.every((v) => typeof v === "number" || (typeof v === "string" && !Number.isNaN(Number(v))));
  if (allNum) return present.every((v) => Number.isInteger(Number(v))) ? "z.number().int()" : "z.number()";
  const allDate = present.every((v) => v instanceof Date || (typeof v === "string" && !Number.isNaN(Date.parse(v))));
  if (allDate) return "z.coerce.date()";
  return "z.string()";
}

function camelCase(s: string): string {
  const parts = s.split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "sheet";
  return parts[0]!.toLowerCase() + parts.slice(1).map((p) => p[0]!.toUpperCase() + p.slice(1).toLowerCase()).join("");
}

function pascalCase(s: string): string {
  const c = camelCase(s);
  return c[0]!.toUpperCase() + c.slice(1);
}

function sizeOrFallback(path: string, fallback: number): number {
  try { return statSync(path).size; } catch { return fallback; }
}

function errorResult(code: string, message: string): StepResult {
  return { ok: false, outputs: {}, fileRefs: [], bytesProcessed: 0, durationMs: 0, error: { code, message } };
}
