/**
 * stl-to-obj: converts STL (binary or ASCII) to OBJ wavefront format.
 */

import { readFile, writeFile } from "node:fs/promises";
import { statSync } from "node:fs";
import { join } from "node:path";
import type { StepResult, FileRef } from "../types.js";
import { parseStl } from "./_stl-utils.js";

interface ToolContext {
  toolId: string;
  inputs: Record<string, unknown>;
  fileRefs: FileRef[];
  scratchDir: string;
  emitProgress(bytes: number): void;
}

export default async function stlToObj(ctx: ToolContext): Promise<StepResult> {
  const start = Date.now();
  const ref = ctx.fileRefs[0];
  if (!ref) return errorResult("missing_input", "stl-to-obj requires one STL input");
  const inPath = join(ctx.scratchDir, ref.ref);
  const totalIn = sizeOrFallback(inPath, ref.bytes);
  const buf = await readFile(inPath);
  ctx.emitProgress(totalIn);
  const tris = parseStl(buf);

  const vertexMap = new Map<string, number>();
  const lines: string[] = ["# Generated by stl-to-obj"];
  const faces: [number, number, number][] = [];
  for (const t of tris) {
    const ids = t.v.map((v) => {
      const k = v.map((c) => c.toFixed(6)).join(",");
      let id = vertexMap.get(k);
      if (id === undefined) {
        id = vertexMap.size + 1;
        vertexMap.set(k, id);
        lines.push(`v ${v[0]} ${v[1]} ${v[2]}`);
      }
      return id;
    }) as [number, number, number];
    faces.push(ids);
  }
  for (const [a, b, c] of faces) lines.push(`f ${a} ${b} ${c}`);
  const obj = lines.join("\n") + "\n";
  const outRef = (ref.filename ?? ref.ref).replace(/\.stl$/i, ".obj");
  await writeFile(join(ctx.scratchDir, outRef), obj, "utf8");
  return { ok: true, outputs: { vertexCount: vertexMap.size, faceCount: faces.length }, fileRefs: [{ ref: outRef, bytes: Buffer.byteLength(obj, "utf8"), sha256: "", mime: "model/obj", filename: outRef }], bytesProcessed: totalIn, durationMs: Date.now() - start };
}

function sizeOrFallback(path: string, fallback: number): number { try { return statSync(path).size; } catch { return fallback; } }
function errorResult(code: string, message: string): StepResult { return { ok: false, outputs: {}, fileRefs: [], bytesProcessed: 0, durationMs: 0, error: { code, message } }; }
